const ProductData=[
    {
        "id":1,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/31TEA0qrUBL._SX300_SY300_QL70_FMwebp_.jpg"
    },
    {
        "id":2,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/31ZXLg+sbHL._SY300_SX300_.jpg"
    },
    {
        "id":3,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/31TEA0qrUBL._SX300_SY300_QL70_FMwebp_.jpg"
    },
    {
        "id":4,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/31TEA0qrUBL._SX300_SY300_QL70_FMwebp_.jpg"
    },
    {
        "id":5,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/61crOmKT32L._SL1000_.jpg"
    },
    {
        "id":6,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/31TEA0qrUBL._SX300_SY300_QL70_FMwebp_.jpg"
    },
    {
        "id":7,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/31TEA0qrUBL._SX300_SY300_QL70_FMwebp_.jpg"
    },
    {
        "id":8,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/31TEA0qrUBL._SX300_SY300_QL70_FMwebp_.jpg"
    },
    {
        "id":9,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/31TEA0qrUBL._SX300_SY300_QL70_FMwebp_.jpg"
    },
    {
        "id":10,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/31TEA0qrUBL._SX300_SY300_QL70_FMwebp_.jpg"
    }
]

export default ProductData;